# Generated by Django 4.2.7 on 2025-10-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["site", "order", "slug"],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Display order in navigation menus"
            ),
        ),
    ]
