# Generated by Django 4.2.7 on 2025-10-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_page_options_page_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Whether the page is published and visible"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="Date and time when page was published", null=True
            ),
        ),
    ]
