# Generated by Django 4.2.7 on 2025-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_add_publishing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageblock",
            name="close_article_tag",
            field=models.BooleanField(
                default=False,
                help_text="Insert closing </article> tag after this block content",
            ),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="open_article_tag",
            field=models.BooleanField(
                default=False,
                help_text="Insert opening <article> tag before this block content",
            ),
        ),
    ]
