# Generated by Django 4.2.7 on 2025-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CssClassList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the class list",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "classes",
                    models.JSONField(default=list, help_text="List of CSS class names"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System lists cannot be deleted (e.g., default lists)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CSS Class List",
                "verbose_name_plural": "CSS Class Lists",
                "db_table": "css_class_lists",
                "indexes": [
                    models.Index(fields=["name"], name="css_class_l_name_83f74d_idx"),
                    models.Index(
                        fields=["is_system"], name="css_class_l_is_syst_2633b2_idx"
                    ),
                ],
            },
        ),
    ]
