# Generated by Django 4.2.7 on 2025-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="service",
            field=models.CharField(
                choices=[
                    ("chatgpt", "ChatGPT"),
                    ("grok", "Grok"),
                    ("claude", "Claude"),
                    ("openrouter", "OpenRouter"),
                    ("cloudflare", "Cloudflare"),
                    ("elevenlabs", "ElevenLabs"),
                    ("dalle", "DALL-E"),
                    ("midjourney", "Midjourney"),
                ],
                max_length=20,
            ),
        ),
    ]
