# Generated by Django 4.2.7 on 2025-10-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_initial"),
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_slug", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site", "page_slug", "timestamp"],
                        name="analytics_p_site_id_fc9094_idx",
                    )
                ],
            },
        ),
    ]
