# Generated by Django 4.2.7 on 2025-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="ai_model",
            field=models.CharField(
                help_text="AI model: gpt-4, gpt-3.5-turbo, claude-3, openai/gpt-4, anthropic/claude-3-sonnet, dall-e-3, etc.",
                max_length=100,
            ),
        ),
    ]
