# Generated by Django 4.2.7 on 2025-10-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0001_initial"),
        ("sites", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sites",
                to="templates.template",
            ),
        ),
    ]
