# Generated by Django 4.2.7 on 2025-10-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0003_alter_site_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="custom_css_class_list",
            field=models.CharField(
                blank=True,
                help_text="Custom CSS class list name for template uniqueness",
                max_length=50,
                null=True,
            ),
        ),
    ]
