# Generated by Django 4.2.7 on 2025-10-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
        ("deployment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="cloudflare_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deployments",
                to="integrations.cloudflaretoken",
            ),
        ),
    ]
