# Generated by Django 4.2.7 on 2025-10-25 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
        ("deployment", "0003_make_cloudflare_token_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="cloudflare_token",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deployments",
                to="integrations.cloudflaretoken",
            ),
            preserve_default=False,
        ),
    ]
