# Generated by Django 4.2.7 on 2025-10-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="media",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
